# Generated by Django 3.1.3 on 2020-11-21 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "date_completed",
                    models.DateTimeField(default=None, verbose_name="date completed"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "List",
                "verbose_name_plural": "Lists",
            },
        ),
        migrations.CreateModel(
            name="ListItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=255, verbose_name="item name"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "date_completed",
                    models.DateTimeField(default=None, verbose_name="date completed"),
                ),
                (
                    "todo_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lists.list",
                        verbose_name="list",
                    ),
                ),
            ],
            options={
                "verbose_name": "List Item",
                "verbose_name_plural": "List Items",
            },
        ),
    ]
