# Generated by Django 3.1.3 on 2020-11-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_completed',
            field=models.DateTimeField(default=None, null=True, verbose_name='date completed'),
        ),
    ]
